### ISSUE TITLE
Portfolio Filtering not working

### ISSUE THREAD

**Issue by cjstolte** [wpexplorer/wpex-adapt#4]
Portfolio filtering does not seem to be working for my site http://cjstolte.com/portfolio/#

**Comment by wpexplorer** [comment]
@cjstolte - Try disabling the jQuery updater plugin you have on your site. It appears to be conflicting with core functions. It's never a good idea to install this plugin, it can also break WordPress core functions. It's always best to load the core version included in WordPress.
